zepp_encryption:
  key: "xeNtBVqzDc6tuNTh"
  iv: "MAAAYAAAAAAAAABg"

# Time range configuration for data fetching
#   days: 1 -> Queries from 12:00 AM (midnight) today to the current time (now)
#   days: 7 -> Queries the last 7 days
default_time_range:
  days: 1

urls:
  tokens: "https://api-user-us2.zepp.com/v2/registrations/tokens"
  login: "https://api-mifit-us2.zepp.com/v2/client/login"
  heart_rate: "https://api-mifit-us3.zepp.com/users/{user_id}/heartRate"
  vo2_max: "https://api-mifit-us3.zepp.com/v2/watch/users/{user_id}/WatchSportStatistics/VO2_MAX"
  sport_load: "https://api-mifit-us3.zepp.com/v2/watch/users/{user_id}/WatchSportStatistics/SPORT_LOAD"
  band_data: "https://api-mifit-us3.zepp.com/v1/data/band_data.json"
  weight: "https://api-mifit-us3.zepp.com/users/{user_id}/members/-1/weightRecords"
  blood_pressure: "https://api-mifit-us3.zepp.com/users/me/bloodPressure"
  user_info: "https://api-mifit-us3.zepp.com/huami.health.getUserInfo.json"
  sport_history: "https://api-mifit-us3.zepp.com/v1/sport/{sport}/history.json"
  user_events: "https://api-mifit-us3.zepp.com/users/{user_id}/events"
  user_events_date_string: "https://api-mifit-us3.zepp.com/users/{user_id}/events/dateString"
  readiness_events: "https://api-mifit-us3.zepp.com/v2/users/me/events"
  second_hr_files: "https://api-mifit-us3.zepp.com/users/me/fileInfo/events"
  manual_data: "https://api-mifit-us3.zepp.com/v1/user/manualData.json"

payloads:
  tokens_payload:
    state: "REDIRECTION"
    client_id: "HuaMi"
    redirect_uri: "https://s3-us-west-2.amazonaws.com/hm-registration/successsignin.html"
    region: "us-west-2"
    token:
      - "access"
      - "refresh"
    country_code: "US"
  login_payload:
    device_model: "android_phone"
    app_version: "9.12.5"
    dn: "api-mifit.zepp.com,api-user.zepp.com,api-mifit.zepp.com,api-watch.zepp.com,app-analytics.zepp.com,auth.zepp.com,api-analytics.zepp.com"
    third_name: "huami"
    source: "com.huami.watch.hmwatchmanager:9.12.5:151689"
    app_name: "com.huami.midong"
    country_code: "US"
    grant_type: "access_token"
    allow_registration: "false"
    lang: "en"
    countryState: "US-NY"

headers:
  tokens_headers:
    app_name: "com.huami.midong"
    appname: "com.huami.midong"
    cv: "151689_9.12.5"
    v: "2.0"
    appplatform: "android_phone"
    vb: "202509151347"
    vn: "9.12.5"
    user-agent: "Zepp/9.12.5 (Pixel 4; Android 12; Density/2.75)"
    x-hm-ekv: "1"
    content-type: "application/x-www-form-urlencoded; charset=UTF-8"
  login_headers:
    app_name: "com.huami.webapp"
    appname: "com.huami.webapp"
    origin: "https://user.zepp.com"
    referer: "https://user.zepp.com/"
    user-agent: "Mozilla/5.0"
    content-type: "application/x-www-form-urlencoded; charset=UTF-8"
  data_headers:
    appname: "com.huami.midong"
    appplatform: "ios_phone"
    accept-encoding: "gzip"
    v: "2.0"
    vn: "10.2.5"
    cv: "1722_10.2.5"
    vb: "202604132257"
    user-agent: "Zepp/10.2.5 (iPhone; iOS 26.3.1; Scale/3.00)"
    lang: "en"
